export type AppRoute =
  | '/'
  | '/components'
  | '/japa'
  | '/japa/focus'
  | '/books'
  | '/verses'
  | '/calendar'
  | '/statistics'
  | '/profile'
  | '/settings'
  | '/auth'
  | '/auth/login'
  | '/auth/register'
  | '/auth/onboarding'
  | '/auth/onboarding/name'
  | '/auth/onboarding/practices'
  | '/auth/onboarding/goals';
